# Generated by Django 3.0.4 on 2020-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='recording',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
