# Generated by Django 3.0.4 on 2020-03-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200305_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='recording',
        ),
        migrations.AddField(
            model_name='result',
            name='progress',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
