# Generated by Django 3.0.4 on 2020-03-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200305_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='result',
        ),
        migrations.RemoveField(
            model_name='result',
            name='goal_met',
        ),
        migrations.AddField(
            model_name='result',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Result'),
        ),
    ]
