# Generated by Django 3.0.4 on 2020-03-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200305_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.Result'),
            preserve_default=False,
        ),
    ]
